version: "3.7"
services:
  backend:
    container_name: node-backend
    image: node:14
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ../backend/:/var/www/

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - TZ=Europe/Moscow
    ports:
      - $MYSQLDB_DOCKER_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql:/var/lib/mysql

  nextjs:
    container_name: nextJs
    image: "node:14"
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/var/www/
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email ithub-company@yandex.ru --agree-tos --no-eff-email -d ithub-portal.ru -d www.ithub-portal.ru
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot