version: "3.7"
services:
  backend:
    container_name: node-backend
    image: node:14
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ../backend/:/var/www/

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - TZ=Europe/Moscow
    ports:
      - $MYSQLDB_DOCKER_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql:/var/lib/mysql

  nextjs:
    container_name: nextJs
    image: "node:14"
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/var/www/

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"